### ISSUE TITLE
Different model layers from wav2letter++?

### ISSUE THREAD

**Issue by htZhang25** [silversparro/wav2letter.pytorch#1]
Hi! I found there are quite obvious differences between your codes in model.py with the original W2lModule.cpp of wav2letter++ written in C++. Also ,It seems this also happens between the previous published wav2letter with wav2letter++ .  Is this due to it's not important about the specific use of the convolutional layers?  Or they're just the same.for I'm not familiar with C++.
Thank you for replying me.

**Comment by vaibhav0195** [comment]
Hi @htZhang25 
The main idea here is to expose the temporal dependencies in the audio using just the convolution layer.
Also if you look at the lua impl of wav2Letter by fb "https://github.com/facebookresearch/wav2letter/tree/wav2letter-lua", you can see the arch defined here is also different from the one described in the paper.
So I think the specific use of convolution layer is not that important in this case and we can use tune those hyper parameters which is best for our usecase.
This repo's arch is based on 
"https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/wave2letter.html"
