### ISSUE TITLE
unable to extract the model file 'wav2Letter_7.pth.tar' 

### ISSUE THREAD

**Issue by kapoorparul** [silversparro/wav2letter.pytorch#10]

**Comment by vaibhav0195** [comment]
Hi please provide a description about the error.
Thanks.

**Comment by malikehtasham222** [comment]
![Capture](https://user-images.githubusercontent.com/53647356/81078136-439b0f80-8f07-11ea-848c-9f304ce95b9a.PNG)

**Comment by vaibhav0195** [comment]
Hi malik,
you dont need to extract the file. simply provide the path of the file to the "--continue-from" variable while running the training of the wav2letter.\
Hope this helps
