### ISSUE TITLE
Stuck when running test.py

### ISSUE THREAD

**Issue by bayupriyanta** [silversparro/wav2letter.pytorch#11]
Hello, I was trying to do training with a custom dataset and managed to produce final_model.pth.rar.
When trying to run the testing.py code, I ran into the following circumstances:

![gambar](https://user-images.githubusercontent.com/18474813/90105227-c554d180-dd6f-11ea-94f5-d36c388fc19d.png)

I waited for more than 10 minutes but the state still doesn't change, (still on 0% progress bar). But when I check on the /usr/bin/top, this task state is still R (running) and using 1 CPU thread

![gambar](https://user-images.githubusercontent.com/18474813/90105304-def61900-dd6f-11ea-894c-8aa8dfdb05a8.png)

not much change is made to the original code, just trying to run from end to end
Has anyone experienced the same thing? Any Idea how to solve it?

**Comment by vaibhav0195** [comment]
Hi,
Can you please share the screen shot of nvidia-smi command while you are running the test.py?
Thanks.

**Comment by vaibhav0195** [comment]
Closing issue as no response was provided. Feel free to reopen.
