### ISSUE TITLE
Steps for Applying this code to another language

### ISSUE THREAD

**Issue by nirmeshshah** [silversparro/wav2letter.pytorch#12]
Hi, 

Can you please share detail steps to apply this repo to another language apart from English.

**Comment by vaibhav0195** [comment]
Hi nirmesh,
I didnt get the question can you please elaborate. ?

**Comment by nirmeshshah** [comment]
> Hi nirmesh,
> I didnt get the question can you please elaborate. ?

Hi, Vaibhav, 

I am planning to apply this repo to one of the Indian languages. I wanted to know apart from giving wav path and corresponding transcript, where should I make changes in order to apply wav2letter repo to one of the Indian languages. For example should I define somewhere symbols/phones corresponding to the Indian languages? Also if there are any other changes one should apply when planning to run wav2letter for another language than English. If anyone can kindly list down, it will be useful

**Comment by vaibhav0195** [comment]
Hi for starters, you can look at the labels.json file where you can define what each character value and there output nodes index.
It will then automatically initialise the output layer with the number of characters you provided in the labels.json.
Also you have to change "parse_transcript" function in the SpectrogramDataset class inside the file data/data_loader.py to load the transcript the language of the indian language.
Hope it helps.
