### ISSUE TITLE
About the lm-path?

### ISSUE THREAD

**Issue by htZhang25** [silversparro/wav2letter.pytorch#2]
Hi,according to
beam_args.add_argument('--lm-path', default="", type=str,
help='Path to an (optional) kenlm language model for use with beam search (req'd with trie)')

What should the lm-path be like, it refers whose path of which specific type of file? if i want to use the kenlm for example using"https://github.com/kpu/kenlm/tree/master/lm"?
Thank you very much!

**Comment by vaibhav0195** [comment]
Hi @htZhang25 
the lm-path should be the absolute path of the ".binary" file generated when you build your language model using the ken-lm. :)

**Comment by htZhang25** [comment]
Do you mean the ".binary"file generated from similiarly the following order：
./kenlm/bin/build_binary bible.arpa bible.binary
That's to say,using lm-path is designed to load the training data input for kenlm, and the kenlm itself is already included in the class  CTCBeamDecoder from ctcdecode module?

**Comment by vaibhav0195** [comment]
@htZhang25 yes use that .binary file
