### ISSUE TITLE
What's your WER on librispeech?

### ISSUE THREAD

**Issue by iamxiaoyubei** [silversparro/wav2letter.pytorch#5]

**Comment by vaibhav0195** [comment]
Hi,
It might take us few weeks to do the same. But it would be great if you could train and post the result here :)
Thanks

**Comment by kilolgupta** [comment]
Hello, any update on this, please?

**Comment by vaibhav0195** [comment]
Hi,
I have provided the link for the pretrained model (trained on librispeech).
Thanks
