### ISSUE TITLE
transcribe.py

### ISSUE THREAD

**Issue by ghost** [silversparro/wav2letter.pytorch#6]
Hi, where is your transribe.py file, or I just need test.py file to do "speech to text" ?

**Comment by vaibhav0195** [comment]
hi , I will update the repo to add the transcribe.py file.
In the meantime yes you can use test.py for the same .

**Comment by vaibhav0195** [comment]
Hi i have uploaded the transcibe.py :)

**Comment by jtdutta1** [comment]
Hi, I am facing this error.

```
Traceback (most recent call last):
  File "transcribe.py", line 86, in <module>
    spect = parser.parse_audio(args.audio_path).contiguous()
AttributeError: 'tuple' object has no attribute 'contiguous'
```

I am running the transcribe.py like this,

`python transcribe.py --model-path models/wav2Letter_7.pth.tar --audio-path ../../data/test_wavs/1320-122612-0000.wav`
