### ISSUE TITLE
Train on multiple GPUs on a single host EC2 instance

### ISSUE THREAD

**Issue by ronanki** [silversparro/wav2letter.pytorch#9]
Do I need to provide any additional arguments to run train.py on multiple GPUs? I see there are some flags for distributed training -- but I'm just focussing on running on multiple GPUs in a single host machine. 

Currently, it's training on a single GPU even though the host has multiple GPUs.

**Comment by vaibhav0195** [comment]
Hi @ronanki 
I havent updated the code to support multi-gpu training yet.

I will add the multi GPU support ASAP.

EDIT : I have updated the readme with the instruction on how to run in multi gpu configration.
Try with the new instructions . 
Thanks.

**Comment by ronanki** [comment]
Thank you very much.

It worked after making a small change in [distributed.py](https://github.com/silversparro/wav2letter.pytorch/blob/master/data/distributed.py#L58) following this [issue](https://github.com/NVIDIA/nv-wavenet/issues/32):
```python
param._execution_engine.queue_callback(allreduce_params)
```
replaced with
```python
Variable._execution_engine.queue_callback(allreduce_params)
```
